name: Collect pythonXY.dll

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  collect:
    name: Collect pythonXY.dll
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11-dev"
      - name: Copy pythonXY.dll
        shell: bash
        run: |
          for VER in 3.7 3.8 3.9 3.10 3.11; do
            VER_NUM=$(echo $VER | sed 's/\.//')
            PREFIX=$(py -$VER -c "import sys; print(sys.base_prefix, end='')")
            cp "$PREFIX/python$VER_NUM.dll" .
          done
          ls *.dll
      - name: Upload DLLs
        uses: actions/upload-artifact@v2
        with:
          name: dll
          path: |
            *.dll
