name: Update stable_abi.txt

on:
  workflow_dispatch:
  schedule:
    # Run every week
    - cron: '0 0 * * 0'

jobs:
  update:
    name: Update stable_abi.txt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch latest stable_abi.txt
      run: |
        curl https://raw.githubusercontent.com/python/cpython/main/Misc/stable_abi.txt > stable_abi.txt
    - name: Parse stable_abi.txt to produce python3.def
      run: |
        ./parse-stable-abi.py < stable_abi.txt > src/python3.def
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        delete-branch: true
        add-paths: |
          src/python3.def
        title: 'Update python3.def using stable_abi.txt from the latest main'
        commit-message: 'chore: Update python3.def using stable_abi.txt from the latest main'
        body: 'Source: https://raw.githubusercontent.com/python/cpython/main/Misc/stable_abi.txt'
